// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoOcr.Infrastructure.Persistence;

#nullable disable

namespace PoOcr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OcrDbContext))]
    partial class OcrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PoOcr.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ACTION");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ACTOR");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("MESSAGE");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("OCCURRED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AUDIT_EVENT", (string)null);
                });

            modelBuilder.Entity("PoOcr.Domain.Drafts.PoDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CUSTOMER_NAME");

                    b.Property<DateOnly?>("PoDate")
                        .HasColumnType("date")
                        .HasColumnName("PO_DATE");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PO_NUMBER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<Guid>("UploadFileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UPLOAD_FILE_ID");

                    b.HasKey("Id");

                    b.HasIndex("PoNumber");

                    b.HasIndex("UploadFileId");

                    b.ToTable("PO_DRAFT", (string)null);
                });

            modelBuilder.Entity("PoOcr.Domain.Drafts.PoDraftLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ITEM_CODE");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(16, 4)
                        .HasColumnType("decimal(16,4)")
                        .HasColumnName("LINE_TOTAL");

                    b.Property<Guid?>("PO_DRAFT_ID")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(16, 6)
                        .HasColumnType("decimal(16,6)")
                        .HasColumnName("QUANTITY");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UNIT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(16, 4)
                        .HasColumnType("decimal(16,4)")
                        .HasColumnName("UNIT_PRICE");

                    b.HasKey("Id");

                    b.HasIndex("PO_DRAFT_ID");

                    b.ToTable("PO_DRAFT_LINE", (string)null);
                });

            modelBuilder.Entity("PoOcr.Domain.Extraction.ExtractionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("COMPLETED_AT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("FAILURE_REASON");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("QUEUED_AT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("STARTED_AT");

                    b.Property<Guid>("UploadFileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UPLOAD_FILE_ID");

                    b.HasKey("Id");

                    b.HasIndex("QueuedAt");

                    b.HasIndex("UploadFileId");

                    b.ToTable("EXTRACTION_JOB", (string)null);
                });

            modelBuilder.Entity("PoOcr.Domain.Uploads.UploadFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("CheckSum")
                        .IsRequired()
                        .HasMaxLength(123)
                        .HasColumnType("varchar(123)")
                        .HasColumnName("CHECKSUM");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CONTENT_TYPE");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("FAILURE_REASON");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ORIGINAL_FILE_NAME");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("SIZE_BYTES");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("StorePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("STORE_PATH");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UPLOADED_AT");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("UPLOADED_BY");

                    b.HasKey("Id");

                    b.HasIndex("CheckSum");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedAt");

                    b.ToTable("UPLOAD_FILE", (string)null);
                });

            modelBuilder.Entity("PoOcr.Domain.Drafts.PoDraftLine", b =>
                {
                    b.HasOne("PoOcr.Domain.Drafts.PoDraft", null)
                        .WithMany("Lines")
                        .HasForeignKey("PO_DRAFT_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PoOcr.Domain.Drafts.PoDraft", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
